[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.1.1", features = [] }

[dependencies]
serde_json = "1.0"
serde_derive = "1.0.145"
serde = { version = "1.0", features = ["derive"] }
hyper = { version = "0.14.20", features = ["full"] }
hyper-tls = "0.5.0"
tauri = { version = "1.1.1", features = ["api-all", "updater"] }
rusqlite = { version = "0.28.0", features = ["bundled"] }
dirs = "4.0"
uuid = { version="1.0.0",feature = ["v4","fast-rng","macro-diagnostics"] }
tokio = { version = "1", features = ["full"] }
[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = [ "custom-protocol" ]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = [ "tauri/custom-protocol" ]

